name: Dry-run Deploy Widgets to Mainnet
on:
  pull_request:
  push:
    branches-ignore:
      - main
jobs:
  deploy-widgets:
    runs-on: ubuntu-latest
    name: Diff from PR
    defaults:
      run:
        working-directory: ./instances/infrastructure-committee.near
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci
      - name: Set replacements
        id: set_replacements
        run: |
          echo "replacements=$(jq -r '[to_entries[] | .["find"] = "${" + .key + "}" | .["replace"] = .value | del(.key, .value), {"find": "${REPL_POSTHOG_API_KEY}", "replace": "'$POSTHOG_API_KEY'"}]' aliases.mainnet.json | tr -d "\n\r")" >> $GITHUB_OUTPUT
      - name: Replace placeholders
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: "**/*.jsx"
          find: "${{ steps.set_replacements.outputs.replacements }}"
          prefix: "(^|.*)"
          suffix: "($|.*)"

      - name: Install bos CLI
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/FroVolod/bos-cli-rs/releases/download/v0.3.6/bos-cli-installer.sh | sh
      - name: Deploy widgets
        run: |
          bos components diff infrastructure-committee.near network-config mainnet
