name: Release
on:
  push:
    branches: [main, ci/add-automatic-deployment-to-nearsocial]
jobs:
  deploy-widgets:
    runs-on: ubuntu-latest
    name: Deploy widgets to near.social (mainnet)
    env:
      NEAR_SOCIAL_ACCOUNT_ID: ${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}
      NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY: ${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}
      NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY: ${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install near-social CLI
      run: |
        sudo apt-get install --assume-yes libudev-dev
        cargo install --git https://github.com/FroVolod/near-social --branch zero-deposit

    - name: Deploy widgets
      run: near-social deploy "$NEAR_SOCIAL_ACCOUNT_ID" network-config mainnet sign-with-plaintext-private-key --signer-public-key "$NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY" --signer-private-key "$NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY" send
